####################################################
# DOWNLOAD TOOLS AND SETUP TOOLS
####################################################
name: "Download Hygiene Check Tools"
description: "Download tools that will evaluate hygiene health of the project"
inputs: { }  # If you don't have any inputs, you can leave it empty or remove this line.
outputs: { }  # If you don't have any outputs, you can leave it empty or remove this line.
runs:
  using: "composite"
  steps:
    ##########################
    # DOWNLOAD CHECKSTYLE
    ##########################

    - name: ?? Download Checkstyle
      run: |
        mkdir tools\checkstyle
        curl -L -o tools\checkstyle\checkstyle-10.26.1-all.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.26.1/checkstyle-10.26.1-all.jar
      shell: cmd

    ##############################
    # DOWNLOAD PMD and SETUP PMD
    ##############################
    - name: ?? Download and Extract PMD
      run: curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.15.0/pmd-dist-7.15.0-bin.zip
      shell: bash


    - name: ?? Extract PMD
      run: |
        mkdir tools\pmd
        powershell -Command "Expand-Archive -Path 'pmd.zip' -DestinationPath 'tools\pmd'"
      shell: cmd
      ##########################
      # DOWNLOAD JACOCO+JUNIT
      ##########################

    - name: ?? Download JaCoCo + JUnit Console
      run: |
        mkdir tools\jacoco-0.8.13\lib
        curl -L -o tools\jacoco-0.8.13\lib\jacocoagent.jar https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.8.13/org.jacoco.agent-0.8.13-runtime.jar
        curl -L -o tools\jacoco-0.8.13\lib\jacococli.jar https://repo1.maven.org/maven2/org/jacoco/org.jacoco.cli/0.8.13/org.jacoco.cli-0.8.13-nodeps.jar
        mkdir tools\junit-console
        curl -L -o tools\junit-console\junit-platform-console-standalone-1.13.0.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.13.0/junit-platform-console-standalone-1.13.0.jar
      shell: cmd

    ##########################
    # DOWNLOAD SONAR-SCANNER
    ##########################

    - name: ?? Download and Setup SonarScanner 7.1.0.4889
      shell: bash
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.1.0.4889-windows-x64.zip
        mkdir tools/sonar-scanner
        unzip sonar-scanner.zip -d tools/sonar-scanner
        echo "SONAR_SCANNER_HOME=$PWD/tools/sonar-scanner-7.1.0.4889-windows" >> $GITHUB_ENV
        echo "$PWD/tools/sonar-scanner/sonar-scanner-7.1.0.4889-windows/bin" >> $GITHUB_PATH         

