package com.hb.study.udemy_lpa_javamasterclass.section6_controlflow.demostubs;

import com.hb.study.udemy_lpa_javamasterclass.global.utils.ConsoleStyler;

import java.util.Scanner;
import java.util.Set;

/*
*   This code has been generated by Microsoft CoPilot
*/

public class QuarterFinder {
        public static void main(String[] unusedArgs) {
        //
        Scanner scanner = new Scanner(System.in);

        // Set of valid month names
        Set<String> validMonths = Set.of(
                "january", "february", "march", "april", "may", "june",
                "july", "august", "september", "october", "november", "december"
        );

        System.out.print("Enter the name of a month: ");
        String month = scanner.nextLine().trim().toLowerCase(); // Normalize input

        // Validate input to allow only month names (no numbers or special characters)
        if (!validMonths.contains(month)) {
            ConsoleStyler.styleOutput("Invalid input! Please enter a valid month name (e.g., January, February, etc.).");
        } else {
            // Enhanced switch statement to determine the quarter
            String quarter = switch (month) {
                case "january", "february", "march" -> "First Quarter (Q1)";
                case "april", "may", "june" -> "Second Quarter (Q2)";
                case "july", "august", "september" -> "Third Quarter (Q3)";
                case "october", "november", "december" -> "Fourth Quarter (Q4)";
                default -> "Unexpected error!"; // Should never reach here
            };

            ConsoleStyler.styleOutput("The month " + capitalize(month) + " falls in the " + quarter + ".");
        }

        scanner.close();
    }

    // Helper method to capitalize the first letter of the month name
    private static String capitalize(String str) {
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
}