##############################################################
# PERFORM HYGIENE HEALTH CHECKS AND UPLOAD REPORTS
##############################################################
name: "Perform Hygiene Health Checks and Upload Reports"
description: ""
inputs:
  SKIP_FLAG:
    description: ""
    required: true

outputs:
  ARTIFACT_URL:
    description: ""
    value: ${{ steps.artifact_url.outputs.ARTIFACT_URL }}
runs:
  using: "composite"
  steps:
    #####################################
    # RUN ALL-HYGIENE SWEEP CHECK
    #####################################
    - name: ALL-HYGIENE SWEEP CHECK (Run hygiene health check analysis via batch script)
      if: success()
      shell: pwsh
      run: |
        $SKIP_FLAG = "${{ inputs.SKIP_FLAG }}"
        # --- DEBUG: show what is being passed
        Write-Host "🧪 SKIP_FLAG received in composite: '$SKIP_FLAG'"
        Write-Host "🧪 SKIP_FLAG as finally being passed to batch script in composite: '$SKIP_FLAG'"
        # Write-Host the environment variable directly to ensure its value is printed.
        Write-Host "🧪 Bash path from previous step: '$env:SONAR_SCANNER_BIN'"
        & scripts/hygiene-check-analysis.bat githubactions $SKIP_FLAG

#    - name: Run SonarCloud Scan
#      if: ${{ !contains(inputs.SKIP_FLAG, '--skip-sonar') }}
#      uses: SonarSource/sonarqube-scan-action@v5.3.1
#      with:
#        args: >
#          -Dsonar.projectKey=my-project
#          -Dsonar.organization=my-org
#          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
#          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
#          # === Mirrors your batch file checks ===
#          -Dsonar.sources=src
#          -Dsonar.java.binaries=target/classes
#          -Dsonar.junit.reportPaths=reports/junit/latest
#          -Dsonar.jacoco.reportPaths=reports/jacoco/jacoco-latest.exec
#          -Dsonar.checkstyle.reportPaths=reports/checkstyle/checkstyle-latest.xml
#          -Dsonar.pmd.reportPaths=reports/pmd/pmd-latest.xml

    ##########################
    # UPLOAD REPORTS
    ##########################

    - name: ?? Upload All Reports
      id: upload_reports
      uses: actions/upload-artifact@v4
      with:
        name: hygiene-check-artifacts-${{ github.run_id }}-${{ github.run_attempt }}
        path: |
          logs/**
          reports/**
        compression-level: 9 # Set to '9' for best compression
          

    - name: Set Artifact Download URL
      id: artifact_url
      shell: pwsh
      run: |
        $artifactId = "${{ steps.upload_reports.outputs.artifact-id }}"
        $repo = "${{ github.repository }}"
        $runId = "${{ github.run_id }}"
        $artifactUrl = "https://github.com/$repo/actions/runs/$runId/artifacts/$artifactId"
        Write-Host "🧪 ARTIFACT_URL as finally being passed downstream: '$artifactUrl'"
        "ARTIFACT_URL=$artifactUrl" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
