# .github/actions/publish-github-summary/action.yaml
##############################################################
# GITHUB  SUMMARY COMPOSITE
##############################################################
name: "Publish GitHub Summary Composite"
description: "Reusable step to send hygiene summary email"
inputs:
  HygieneCheckStatus:
    required: true
    description: ""
  NextStepsHtml:
    required: true
    description: ""
  BRANCH_EXECUTED:
    required: true
    description: ""
  sonarCoverage:
    required: true
    description: ""
  coverageBar:
    required: true
    description: ""
  checkstyleCount:
    required: true
    description: ""
  pmdCount:
    required: true
    description: ""
  sonarExecutionNote:
    required: true
    description: ""
  sonarIssuesNote:
    required: true
    description: ""
  lastSonarAnalysis:
    required: true
    description: ""
  sonarBlocker:
    required: true
    description: ""
  sonarBlockerUrl:
    required: true
    description: ""
  sonarBlockerEmojiMark:
    required: true
    description: ""
  sonarHigh:
    required: true
    description: ""
  sonarHighUrl:
    required: true
    description: ""
  sonarHighEmojiMark:
    required: true
    description: ""
  sonarMedium:
    required: true
    description: ""
  sonarMediumUrl:
    required: true
    description: ""
  sonarMediumEmojiMark:
    required: true
    description: ""
  sonarLow:
    required: true
    description: ""
  sonarLowUrl:
    required: true
    description: ""
  sonarLowEmojiMark:
    required: true
    description: ""
  sonarInfo:
    required: true
    description: ""
  sonarInfoUrl:
    required: true
    description: ""
  sonarInfoEmojiMark:
    required: true
    description: ""
  sonarOpenIssuesDashboardURL:
    required: true
    description: ""
  sonarOverallCodeDashBoardURL:
    required: true
    description: ""
  EMAIL_MODULE_SEV_AGG_TABLE:
    required: true
    description: ""
  FULL_SHA:
    required: true
    description: ""
  SHORT_SHA:
    required: true
    description: ""
  TRIGGER_INFO:
    required: true
    description: ""
  COMMIT_MSG:
    required: true
    description: ""
  COMMIT_AUTHOR:
    required: true
    description: ""
  COMMIT_DATE:
    required: true
    description: ""
  startTime:
    required: true
    description: ""
  endTime:
    required: true
    description: ""
  formattedDuration:
    required: true
    description: ""
  ARTIFACT_URL:
    required: true
    description: ""
  STAGE_VS_MAIN_STATE:
    required: true
    description: ""
  sonarIssuesLegend:
    required: true
    description: ""
  GITHUB_SUMMARY_MODULE_SEV_AGG_TABLE:
    required: true
    description: ""

runs:
  using: "composite"
  steps:
    ####################################################
    # Publish GITHUB SUMMARY
#      $branch                = "${{ inputs.BRANCH_EXECUTED }}"
#      $repository            = "${{ github.repository }}"
#      $checkstyleViolations  = "${{ inputs.checkstyleCount }}"
#      $pmdViolations         = "${{ inputs.pmdCount }}"
#      $sonarCoverage         = "${{ inputs.sonarCoverage }}"
#      $coverageStatus        = "${{ inputs.coverageStatus }}"
#      $coverageBar           = "${{ inputs.coverageBar }}"
#      $sonarExecutionNote    = "${{ inputs.sonarExecutionNote }}"
#      $sonarIssuesNote       = "${{ inputs.sonarIssuesNote }}"
#      $lastSonarAnalysis     = "${{ inputs.lastSonarAnalysis }}"
#      $sonarBlocker          = "${{ inputs.sonarBlocker }}"
#      $sonarBlockerUrl       = "${{ inputs.sonarBlockerUrl }}"
#      $sonarBlockerEmojiMark = "${{ inputs.sonarBlockerEmojiMark }}"
#      $sonarHigh             = "${{ inputs.sonarHigh }}"
#      $sonarHighUrl          = "${{ inputs.sonarHighUrl }}"
#      $sonarHighEmojiMark    = "${{ inputs.sonarHighEmojiMark }}"
#      $sonarMedium           = "${{ inputs.sonarMedium }}"
#      $sonarMediumUrl        = "${{ inputs.sonarMediumUrl }}"
#      $sonarMediumEmojiMark  = "${{ inputs.sonarMediumEmojiMark }}"
#      $sonarLow              = "${{ inputs.sonarLow }}"
#      $sonarLowUrl           = "${{ inputs.sonarLowUrl }}"
#      $sonarLowEmojiMark     = "${{ inputs.sonarLowEmojiMark }}"
#      $sonarInfo             = "${{ inputs.sonarInfo }}"
#      $sonarInfoUrl          = "${{ inputs.sonarInfoUrl }}"
#      $sonarInfoEmojiMark    = "${{ inputs.sonarInfoEmojiMark }}"
#      $sonarOverallUrl       = "${{ inputs.sonarOverallCodeDashBoardURL }}"
#      $sonarOpenIssuesUrl    = "${{ inputs.sonarOpenIssuesDashboardURL }}"
#      $moduleTableHtml       = "${{ inputs.GITHUB_SUMMARY_MODULE_SEV_AGG_TABLE }}"
#      $sonarLegend           = "${{ inputs.sonarIssuesLegend }}"
#      $stageState            = "${{ inputs.STAGE_VS_MAIN_STATE }}"
    ####################################################
    - name: Publish GITHUB Summary
      id: publish-github-summary
      shell: pwsh
      run: |
          $branch = "${{ inputs.BRANCH_EXECUTED }}"
          $repository = "${{ github.repository }}"
          $checkstyleViolations = "${{ inputs.checkstyleCount }}"
          $pmdViolations = "${{ inputs.pmdCount }}"
          $sonarCoverage = "${{ inputs.sonarCoverage }}"
          $coverageStatus = "${{ inputs.coverageStatus }}"
          $coverageBar="${{ inputs.coverageBar }}"
        
           ############################################################
                     # === Write Overall Table ===
           ############################################################
           echo "### ðŸ“Š Hygiene Summary (Checkstyle + PMD + JaCoCo + Sonar)" >> $env:GITHUB_STEP_SUMMARY
           echo "Repository: $repository " >> $env:GITHUB_STEP_SUMMARY
           echo "Branch: $branch" >> $env:GITHUB_STEP_SUMMARY
           echo "Stage â†” Main state: ${{inputs.STAGE_VS_MAIN_STATE }}" >> $env:GITHUB_STEP_SUMMARY
           echo "| **Metric**               | **Value** |" >> $env:GITHUB_STEP_SUMMARY
           echo "|------------------------- |-----------|" >> $env:GITHUB_STEP_SUMMARY
           echo "| ðŸ“ˆ Code Coverage (Sonar)    | $sonarCoverage $coverageStatus |" >> $env:GITHUB_STEP_SUMMARY
           echo "| ðŸŽ¯ Coverage Visual          | <code>$coverageBar</code> |" >> $env:GITHUB_STEP_SUMMARY
           echo "| ðŸ“ Checkstyle Violations    | $checkstyleViolations |" >> $env:GITHUB_STEP_SUMMARY
           echo "| ðŸ” PMD Violations           | $pmdViolations |" >> $env:GITHUB_STEP_SUMMARY00
           echo "| ðŸ—‚ SonarCloud                | Execution: <code>${{inputs.sonarExecutionNote}}</code><br/>Issues: <code>${{inputs.sonarIssuesNote}}</code><br/>Last Analysis: <code>${{inputs.lastSonarAnalysis }}</code> |" >> $env:GITHUB_STEP_SUMMARY
           echo "| ðŸŸ¥ BLOCKER                   | [${{ inputs.sonarBlocker }}](${{ inputs.sonarBlockerUrl }}) ${{ inputs.sonarBlockerEmojiMark }} |" >> $env:GITHUB_STEP_SUMMARY
           echo "| ðŸŸ§ HIGH                      | [${{ inputs.sonarHigh }}](${{ inputs.sonarHighUrl }}) ${{ inputs.sonarHighEmojiMark }} |" >> $env:GITHUB_STEP_SUMMARY
           echo "| ðŸŸ¨ MEDIUM                    | [[${{ inputs.sonarMedium }}](${{ inputs.sonarMediumUrl }}) ${{ inputs.sonarMediumEmojiMark }} |" >> $env:GITHUB_STEP_SUMMARY
           echo "| ðŸŸ¦ LOW                       | [[${{ inputs.sonarLow }}](${{ inputs.sonarLowUrl }}) ${{ inputs.sonarLowEmojiMark }} |" >> $env:GITHUB_STEP_SUMMARY
           echo "| â„¹ INFO                       | [[${{ inputs.sonarInfo }}](${{ inputs.sonarInfoUrl }}) ${{ inputs.sonarInfoEmojiMark }} |" >> $env:GITHUB_STEP_SUMMARY
           echo "| Legend                       | ${{ inputs.sonarIssuesLegend }} |" >> $env:GITHUB_STEP_SUMMARY
           echo "ðŸŒ [View SonarCloud Overall Code Dashboard](${{ inputs.sonarOverallCodeDashBoardUrl }})" >> $env:GITHUB_STEP_SUMMARY
           echo "ðŸŒ [View SonarCloud Issues Breakdown Dashboard](${{ inputs.sonarOpenIssuesDashboardUrl }})" >> $env:GITHUB_STEP_SUMMARY
           echo "${{ inputs.GITHUB_SUMMARY_MODULE_SEV_AGG_TABLE }}" >> $env:GITHUB_STEP_SUMMARY

