##############################################################
# PERFORM HYGIENE HEALTH CHECKS AND UPLOAD REPORTS
##############################################################
name: "Perform Hygiene Health Checks and Upload Reports"
description: ""
inputs: { }  # If you don't have any inputs, you can leave it empty or remove this line.
outputs: { } # If you don't have any inputs, you can leave it empty or remove this line.
runs:
  using: "composite"
  steps:
    #####################################
    # RUN ALL-HYGIENE SWEEP CHECK
    #####################################
    - name: ALL-HYGIENE SWEEP CHECK (Run hygiene health check analysis via batch script)
      if: success()
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        TRIGGER_BRANCH: ${{ github.ref_name }}
        TRIGGER_EVENT: ${{ github.event_name }}
        SOURCE_BRANCH: ${{ github.head_ref }}
      shell: pwsh
      run: |
        Write-Host "🔎 Evaluating Sonar execution rules..."
        
        # Get last commit message
        $COMMIT_MSG = (git log -1 --pretty=%B).Trim()
        
        # Default: skip sonar
        $SKIP_FLAG = "--skip-sonar"
        
        # Reason: for final value of flag
        $REASON = ""
        
        # Case 1: Manual override via commit message
        if ($COMMIT_MSG -match "--skip-sonar") {
          $SKIP_FLAG = "--skip-sonar"
          $REASON = "⚡ Case 1: Manual override → SKIP Sonar in commit message"
        }
        # Case 2: Schedule event → always run sonar
        elseif ($env:TRIGGER_EVENT -ieq "schedule") {
          $SKIP_FLAG = ""
          $REASON = "⚡ Case 2: Scheduled run → RUN Sonar"
        }
        
        # Case 3: Direct commit to main → run sonar
        elseif ($env:TRIGGER_BRANCH -ieq "main" -and [string]::IsNullOrEmpty($env:SOURCE_BRANCH)) {
          $SKIP_FLAG = ""
          $REASON = "⚡ Case 3: Direct commit to main → RUN Sonar"
        }
        
        # Case 4: PR from stage → main
        elseif ($env:TRIGGER_BRANCH -ieq "main" -and $env:SOURCE_BRANCH -ieq "stage") {
          $SKIP_FLAG = ""
          $REASON = "⚡ Case 4: PR from stage → RUN Sonar"          
        }
        
        # Case 5: PR from feature/* → main
        elseif ($env:TRIGGER_BRANCH -ieq "main" -and $env:SOURCE_BRANCH -like "feature/*") {
          $SKIP_FLAG = ""
          $REASON = "⚡ Case 5: PR from feature/* → RUN Sonar"
        }      
        # Otherwise, sonar skipped
        else {
          $REASON = "⚡ Default: Skip conditions → SKIP Sonar"
        }
        # Log final decision
        if ([string]::IsNullOrEmpty($SKIP_FLAG)) {
          Write-Host "✅ Sonar will RUN | $REASON"
        } else {
          Write-Host "⏭️ Sonar will SKIP | $REASON"
        }        
        & scripts/hygiene-check-analysis.bat githubactions $SKIP_FLAG

    ##########################
    # UPLOAD REPORTS
    ##########################

    - name: ?? Upload All Reports
      uses: actions/upload-artifact@v4
      with:
        name: hygiene-reports
        path: |
          reports/**
          logs/**