##############################################################
# PERFORM HYGIENE HEALTH CHECKS AND UPLOAD REPORTS
##############################################################
name: "Perform Hygiene Health Checks and Upload Reports"
description: ""
inputs: { }  # If you don't have any inputs, you can leave it empty or remove this line.
outputs: { } # If you don't have any inputs, you can leave it empty or remove this line.
runs:
  using: "composite"
  steps:
    #####################################
    # RUN ALL-HYGIENE SWEEP CHECK
    #####################################
    - name: ALL-HYGIENE SWEEP CHECK ( Run hygiene health check analysis using via batch script )
      if: success()
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        TRIGGER_BRANCH: ${{ github.ref_name }}
        TRIGGER_EVENT: ${{ github.event_name }}
      run: |
        # Enable strict mode
        Set-StrictMode -Version Latest
        
        Write-Host "🧹 All Hygiene Workflow — Checkstyle then PMD then JaCoCo then SonarCloud"
        
        # Get last commit message
        $commitMsg = git log -1 --pretty=%B
        
        Write-Host "Last commit message:" $commitMsg
        
        # Default: skip Sonar
        $skipFlag = "--skip-sonar"
        
        # Only run Sonar for main/stage/feature branches or scheduled runs
        if ($env:TRIGGER_BRANCH -ieq "main") {
            if ($env:GITHUB_HEAD_REF) {
                if ($env:GITHUB_HEAD_REF -ieq "stage") { $skipFlag = "" }
                elseif ($env:GITHUB_HEAD_REF.StartsWith("feature/", [System.StringComparison]::InvariantCultureIgnoreCase)) {
                    $skipFlag = ""
                }
            }
        }
        if ($env:TRIGGER_EVENT -ieq "schedule") { $skipFlag = "" }
        
        # Manual override via commit message
        if ($commitMsg -match "--execute-sonar") { $skipFlag = "" }
        
        Write-Host "Running hygiene checks with flag:" $skipFlag
        # DISPLAY final value of the flag
        Write-Host "✅ Final SKIP_FLAG value being passed to script:" $skipFlag
        
        # Call batch script with optional flag
        & scripts\hygiene-check-analysis.bat githubactions $skipFlag
      shell: pwsh
    

    ##########################
    # UPLOAD REPORTS
    ##########################

    - name: ?? Upload All Reports
      uses: actions/upload-artifact@v4
      with:
        name: hygiene-reports
        path: |
          reports/**
          logs/**