##############################################################
# PERFORM HYGIENE HEALTH CHECKS AND UPLOAD REPORTS
##############################################################
name: "Perform Hygiene Health Checks and Upload Reports"
description: ""
inputs: { }  # If you don't have any inputs, you can leave it empty or remove this line.
outputs: { } # If you don't have any inputs, you can leave it empty or remove this line.
runs:
  using: "composite"
  steps:
    #####################################
    # RUN ALL-HYGIENE SWEEP CHECK
    #####################################
    - name: ALL-HYGIENE SWEEP CHECK (Run hygiene health check analysis via batch script)
      if: success()
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        TRIGGER_BRANCH: ${{ github.ref_name }}
        TRIGGER_EVENT: ${{ github.event_name }}
        SOURCE_BRANCH: ${{ github.head_ref }}
      shell: pwsh
      run: |
        Write-Host "🔎 Evaluating Sonar execution rules..."
        
        # Get last commit message
        $COMMIT_MSG = (git log -1 --pretty=%B).Trim()
        
        # Default: skip sonar
        $SKIP_FLAG = "--skip-sonar"
        
        # Case 1: Schedule event → always run sonar
        if ($env:TRIGGER_EVENT -ieq "schedule") {
          $SKIP_FLAG = ""
          Write-Host "Reason: Scheduled run"
        }
        
        # Case 2: Direct commit to main → run sonar
        elseif ($env:TRIGGER_BRANCH -ieq "main" -and [string]::IsNullOrEmpty($env:SOURCE_BRANCH)) {
          $SKIP_FLAG = ""
          Write-Host "Reason: Direct commit to main"
        }
        
        # Case 3: PR from stage → main
        elseif ($env:TRIGGER_BRANCH -ieq "main" -and $env:SOURCE_BRANCH -ieq "stage") {
          $SKIP_FLAG = ""
          Write-Host "Reason: stage → main"
        }
        
        # Case 4: PR from feature/* → main
        elseif ($env:TRIGGER_BRANCH -ieq "main" -and $env:SOURCE_BRANCH -like "feature/*") {
          $SKIP_FLAG = ""
          Write-Host "Reason: feature/* → main"
        }
        
        # Case 5: Manual override via commit message
        elseif ($COMMIT_MSG -match "--execute-sonar") {
          $SKIP_FLAG = ""
          Write-Host "Reason: Manual override in commit message"
        }
        
        # Otherwise, sonar skipped
        else {
          Write-Host "Reason: Default skip conditions"
        }
        
        Write-Host "✅ Final SKIP_FLAG value being passed to script: $SKIP_FLAG"
        & scripts/hygiene-check-analysis.bat githubactions $SKIP_FLAG
    

    ##########################
    # UPLOAD REPORTS
    ##########################

    - name: ?? Upload All Reports
      uses: actions/upload-artifact@v4
      with:
        name: hygiene-reports
        path: |
          reports/**
          logs/**