##############################################################
      # PERFORM HYGIENE HEALTH CHECKS AND UPLOAD REPORTS
##############################################################
name: "Perform Hygiene Health Checks and Upload Reports"
description: ""
inputs: {}  # If you don't have any inputs, you can leave it empty or remove this line.
outputs: {} # If you don't have any inputs, you can leave it empty or remove this line.
runs:
  using: "composite"
  steps:
        #####################################
        # RUN ALL-HYGIENE SWEEP CHECK
        #####################################
        - name: ALL-HYGIENE SWEEP CHECK ( Run hygiene health check analysis using via batch script )
          if: success()
          env:
            SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          run: |
            @echo off
            setlocal EnableDelayedExpansion
    
             :: Get the last commit message locally
            for /f "delims=" %%M in ('git log -1 --pretty=%%B') do set "COMMIT_MSG=%%M"
            
            :: Initialize flag variable
            set "SKIP_FLAG="
        
            :: Check for --skip-sonar in the commit message
            echo !COMMIT_MSG! | findstr /I "--skip-sonar" >nul && set "SKIP_FLAG=--skip-sonar"
        
            :: Call the batch script with the optional flag
            scripts\hygiene-check-analysis.bat githubactions !SKIP_FLAG!
            
            endlocal
          shell: cmd


        ##########################
        # UPLOAD REPORTS
        ##########################

        - name: ?? Upload All Reports
          uses: actions/upload-artifact@v4
          with:
            name: hygiene-reports
            path: |
              reports/**
              logs/**