name: DEMO WORKFLOW - VARIOUS ASPECTS
on:
  workflow_dispatch: # run manually
jobs:
  demo:
    name: Demonstrate various aspects of GITHUB Actions # (like : Composite Actions and Conditional Step Execution)
    env:
      SKIP_ECHO: true
    runs-on: ubuntu-latest
    steps:
      - name: ?? Checkout Code
        uses: actions/checkout@v4
        with:
           fetch-depth: 0
      - name: Capture a value (pretend this came from another step)
        id: capture
        run: echo "name=HemantBellani" >> $GITHUB_OUTPUT

      - name: Call Composite Action
        id: process
        uses: ./.github/actions/demo-composite-action
        with:
          username: ${{ steps.capture.outputs.name }}

      - name: Use output in summary
        run: |
          echo "Original name: ${{ steps.process.outputs.originalName }}"
          echo "Uppercased: ${{ steps.process.outputs.upperName }}"
      ###################################################################
      # DEMONSTRATES, FLAG BASED EXECUTION
      ##################################################################

      - name: ??? Say Hello (unless skipped)
        if: env.SKIP_ECHO != 'true'
        run: echo Hello, world!
        shell: cmd

      - name: Use output in Email step (toy example)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ vars.SMTP_SERVER_ADDRESS }}
          server_port: ${{ vars.SMTP_SERVER_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Processed for ${{ steps.process.outputs.upperName }}"
          to: hemantbellanilearns77@gmail.com
          from: github-actions@example.com
          body: |
            Hello ${{ steps.process.outputs.originalName }},
            Your processed variant is: ${{ steps.process.outputs.upperName }}.

