name: Run PMD

on:
  push:
    branches:
      - main

jobs:
  pmd:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download and Extract PMD
        run: |
          curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.15.0/pmd-dist-7.15.0-bin.zip
          mkdir tools\pmd\pmd-dist-7.15.0-bin
          tar -xf pmd.zip -C tools\pmd\pmd-dist-7.15.0-bin
        shell: cmd

      - name: Verify PMD Directory
        run: dir /s /b tools\pmd
        shell: cmd

      - name: Run PMD Analysis
        run: scripts\run-pmd.bat
        shell: cmd

      - name: Upload PMD Reports
        uses: actions/upload-artifact@v4
        with:
          name: pmd-reports
          path: |
            reports/pmd
            logs/pmd-analysis-logs
