name: Run PMD

on:
  push:
    branches:
      - main

jobs:
  pmd:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List directory structure for debug
        run: dir /s /b
        shell: cmd

      - name: Download PMD CLI (v7.15.0)
        run: |
          mkdir tools\pmd
          curl -L -o tools\pmd\pmd-dist.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.15.0/pmd-dist-7.15.0-bin.zip
          powershell -Command "Expand-Archive -Path tools\pmd\pmd-dist.zip -DestinationPath tools\pmd"

      - name: Run PMD Analysis Script
        run: scripts\run-pmd.bat

      - name: Upload PMD Reports
        uses: actions/upload-artifact@v4
        with:
          name: pmd-reports
          path: |
            reports\pmd
            logs\pmd-analysis-logs
