name: Demo Composite Action
on:
  workflow_dispatch: # run manually
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: ?? Checkout Code
        uses: actions/checkout@v4
        with:
           fetch-depth: 0
      - name: Capture a value (pretend this came from another step)
        id: capture
        run: echo "name=HemantBellani" >> $GITHUB_OUTPUT

      - name: Call Composite Action
        id: process
        uses: ./.github/actions/test-action
        with:
          username: ${{ steps.capture.outputs.name }}

      - name: Use output in summary
        run: |
          echo "Original name: ${{ steps.process.outputs.originalName }}"
          echo "Uppercased: ${{ steps.process.outputs.upperName }}"

      - name: Use output in Email step (toy example)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ vars.SMTP_SERVER_ADDRESS }}
          server_port: ${{ vars.SMTP_SERVER_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Processed for ${{ steps.process.outputs.upperName }}"
          to: hemantbellanilearns77@gmail.com
          from: github-actions@example.com
          body: |
            Hello ${{ steps.process.outputs.originalName }},
            Your processed variant is: ${{ steps.process.outputs.upperName }}.
